# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b29d4bd0d997f88ef54bbef6efa66f331a9e263e7a57585a2ed3d7ff0bb48fe30d0664d5af59164b6e349cb9dca30b7f573cedc37931a0a3c49af8382918a64b

test:
  secret_key_base: 55618796634e0afff674a358b61253edf94cde43976473795131962f41817c5b041a8b4dfab15a1fdeb0743a28ad8ff9acb4ba6c799ca162477ffec0ff98a13c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
